### ISSUE TITLE
Add selection of parts by index

### ISSUE THREAD

**Issue by jmairboeck** [aleutgeb/STEPToMesh#7]
(as discussed [in Mattermost](https://mattermost.risc-software.at/risc-users-int/pl/gip8fpzhybrzzdb3htgyugxrba))

To accomodate STEP files with duplicate NamedSolids, the part selection (`-s` argument) should be made possible by indices in addition to names.

**Comment by aleutgeb** [comment]
Was fixed in https://github.com/aleutgeb/STEPToMesh/commit/2bb97cf7bdef57d8981c155e2f498bca2d5cb65b

**Comment by jmairboeck** [comment]
Index based selection works great, even mixed with names. Thanks!
